require File.expand_path(File.dirname(__FILE__) + '/spec_helper')


require 'rspec'
require 'pp'


describe 'sam iterator' do
  it 'should work' do
    sam = 'ERR006982.591   16      4404224 107     0       183M67S *       0       0       GTGCGTAACGCGTATCAAACCTGCCTCATACTCGGGGATAGCCTTGCGAAAGTAAGATTAATACCCGATGTTGTTGCTTTCTCGCATGGGAGAGTAACCAAAGATTTATCGGTATGAGATGGTGATGCGTCCGATTAGGTAGTAGGCGGGGTAACGGCCCACCTAGCCTTCGATCGGTAGGGGGTTCTGAGAGGAAGGTCCCCCACATTGGAACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCATG  *
ERR006982.591   16      104843  241     1       125S59M1I65M    *       0       0       GTGCGTAACGCGTATCAAACCTGCCTCATACTCGGGGATAGCCTTGCGAAAGTAAGATTAATACCCGATGTTGTTGCTTTCTCGCATGGGAGAGTAACCAAAGATTTATCGGTATGAGATGGTGATGCGTCCGATTAGGTAGTAGGCGGGGTAACGGCCCACCTAGCCTTCGATCGGTAGGGGGTTCTGAGAGGAAGGTCCCCCACATTGGAACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCATG  *       '.gsub(/\s+/,"\t")

    iterator = Bio::SamIterator.new(StringIO.new sam)
    sams = iterator.to_a
    sams.length.should == 1
  end
  it 'should work with non the same inputs' do
    sam = 'ERR006982.591   16      4404224 107     0       183M67S *       0       0       GTGCGTAACGCGTATCAAACCTGCCTCATACTCGGGGATAGCCTTGCGAAAGTAAGATTAATACCCGATGTTGTTGCTTTCTCGCATGGGAGAGTAACCAAAGATTTATCGGTATGAGATGGTGATGCGTCCGATTAGGTAGTAGGCGGGGTAACGGCCCACCTAGCCTTCGATCGGTAGGGGGTTCTGAGAGGAAGGTCCCCCACATTGGAACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCATG  *
ERR006982.592   16      104843  241     1       125S59M1I65M    *       0       0       GTGCGTAACGCGTATCAAACCTGCCTCATACTCGGGGATAGCCTTGCGAAAGTAAGATTAATACCCGATGTTGTTGCTTTCTCGCATGGGAGAGTAACCAAAGATTTATCGGTATGAGATGGTGATGCGTCCGATTAGGTAGTAGGCGGGGTAACGGCCCACCTAGCCTTCGATCGGTAGGGGGTTCTGAGAGGAAGGTCCCCCACATTGGAACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCATG  *       '.gsub(/\s+/,"\t")

    iterator = Bio::SamIterator.new(StringIO.new sam)
    sams = iterator.to_a
    sams.length.should == 2
  end
end
